version: '3'
services:
  api:
    container_name: "api"
    build: "."
    volumes:
      - ".:/app"
    ports:
      - "8080:8080"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"